courses/urls.py
from django.urls import re_path
from . import views

app_name = 'courses'
urlpatterns = [
    re_path(r'^$', views.CoursesListView.as_view(), name='courses_index'),
    re_path(r'^(?P<pk>\d+)/$', views.CoursesUrlView.as_view(), name='links')
]

main_app/urls.py
from django.conf.urls import url
from main_app import views

app_name = 'main_app'
urlpatterns = [
    url(r'contacts/$', views.Contacts.as_view(), name="contacts"),
    url('contacts/thank_you/$', views.ContactsThankYou.as_view(), name='contacts_thank_you'),
    url(r'order/$', views.Order.as_view(), name="order"),
    url('order/thank_you/$', views.OrderThankYou.as_view(), name='order_thank_you'),
    url(r'Rady/$', views.Rady.as_view(), name="Rady"),
]

rady_and_stars/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include
from main_app import views
from django.contrib.auth import views as login_view
from . import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^$', views.Index.as_view(), name='index'),
                  url(r'site/', include('main_app.urls')),
                  url(r'userportal/', include('user_content.urls', namespace='user_site')),
                  url(r'login/', login_view.LoginView.as_view(template_name='user_content/login.html'),
                      name='user_login'),
                  url(r'logout/', login_view.logout, name="logout", kwargs={'next_page': 'index'}),
                  url(r'password_reset', login_view.PasswordResetView, name='password_reset'),
                  url(r'admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'__debug__', include(debug_toolbar.urls)),
                  ] + urlpatterns

user_content/urls.py
from django.conf.urls import url, include
from user_content import views
from django.contrib.auth.views import PasswordChangeView

app_name = 'user_content'

urlpatterns = [
    url(r'register/', views.UserRegister.as_view(), name="register"),
    url(r'index/', views.Index.as_view(), name='index'),
    url(r'profile/', views.user_profile_view, name='profile'),
    url(r'horoscope_list/', views.UserHoroscopesListView.as_view(), name="horoscope_list"),
    url(r'detail_text(?P<pk>\d+)/', views.UserHoroscopesDetailView.as_view(), name="detail"),
    url(r'courses/', include('courses.urls', namespace='user_courses')),
    url(r'tarot/', include('tarot_of_the_day.urls', namespace='user_tarot')),
    url(r'daily_tarot_list', views.UserTarotListView.as_view(), name='profile_tarot_list'),
    url(r'daily_tarot_detail(?P<pk>\d+)', views.UserTarotDetailView.as_view(), name='profile_tarot_detail'),
    url(r'daily_tarot_note_edit(?P<pk>\d+)', views.UserTarotNoteUpdateView.as_view(), name='profile__tarot_note_edit'),
    url(r'settings/', views.UserSettingsListView.as_view(), name='settings'),
    url(r'extra_settings_edit', views.UserExtraSettingsUpdateView.as_view(), name='extra_settings'),
    url(r'main_settings_edit', views.UserMainSettingsUpdateView.as_view(), name='main_settings'),
    url(r'password_change',
        PasswordChangeView.as_view(template_name='user_content/profile_settings_password_change.html',
                                   success_url='/login/'),
        name='password_change'),
    url(r'change_avatar', views.profile_pic_upload, name='profile_pic'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class MenuItems(models.Model):
    menu_number = models.IntegerField(primary_key=True, unique=True)
    menu_item = models.CharField(max_length=50)
    menu_link = models.CharField(max_length=200)
    # # За промяната на менюто за логнати потребители. True е ако има логнат потребител.
    logged_in = models.BooleanField()


class SiteContacts(models.Model):
    names = models.CharField(max_length=300, blank=False)
    email = models.EmailField(max_length=100, blank=True)
    phone = models.CharField(max_length=50, blank=False)
    message = models.CharField(max_length=1000, blank=False)
    message_replied = models.BooleanField(default=False)


class SiteOrders(models.Model):
    order_select = (('пълен', 'Пълен астрологичен пакет'), ('единичен', 'Хороскоп на един човек и прогноза'),
                    ('по тема', 'Разглеждане на една тема в хороскопа и прогноза'),
                    ('таро', 'Отговор на до 4 въпроса с таро'))
    names = models.CharField(max_length=300, blank=False)
    email = models.EmailField(max_length=100, blank=True)
    phone = models.CharField(max_length=50, blank=False)
    service_requested = models.CharField(choices=order_select, blank=False, max_length=300)
    add_info = models.CharField(max_length=1000, blank=True)
    request_finished = models.BooleanField(default=False)

main_app/forms.py
from django import forms
from django.forms import models
from main_app.models import SiteContacts, SiteOrders


class SiteContactsForm(models.ModelForm):
    class Meta:
        model = SiteContacts
        fields = ('names', 'email', 'phone', 'message')
        widgets = {
            'names': forms.TextInput(attrs={
                'placeholder': '*Имена*',
            }),
            'email': forms.TextInput(attrs={
                'placeholder': 'Еmail',
            }),
            'phone': forms.TextInput(attrs={
                'placeholder': '*Tелефон*',
            }),
            'message': forms.widgets.Textarea(attrs={
                'placeholder': '*Моля въведете Вашите въпрос*',
                'rows': "6",
            }),
        }


class SiteOrderForm(models.ModelForm):
    class Meta:
        model = SiteOrders
        fields = ('names', 'email', 'phone', 'service_requested', 'add_info')
        widgets = {
            'names': forms.TextInput(attrs={
                'placeholder': '*Имена*',

            }),
            'email': forms.TextInput(attrs={
                'placeholder': 'Email',
            }),
            'phone': forms.TextInput(attrs={
                'placeholder': '*Телефон*',
            }),
            'add_info': forms.widgets.Textarea(attrs={
                'placeholder': 'Допълнителни указания',
                'rows': "6",
            }),

        }

main_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from main_app.forms import SiteContactsForm, SiteOrderForm
from django.views.generic import TemplateView, CreateView


# Create your views here.

class Index(TemplateView):
    template_name = 'main_app/index.html'


class OrderThankYou(TemplateView):
    template_name = 'main_app/order_thank_you.html'


class ContactsThankYou(TemplateView):
    template_name = 'main_app/contacts_thank_you.html'


class Order(CreateView):
    form_class = SiteOrderForm
    template_name = 'main_app/order.html'
    success_url = reverse_lazy('main_app:order_thank_you')


class Rady(TemplateView):
    template_name = 'main_app/Rady.html'


class Contacts(CreateView):
    template_name = 'main_app/contacts.html'
    form_class = SiteContactsForm
    success_url = reverse_lazy('main_app:contacts_thank_you')

templates/main_app/Rady.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block body_contents %}

    <section id="two" class="wrapper style2">
        <div class="inner">
            <div class="box">
                <div class="content">
                    <header class="align-center">
                        <p>Твоят личен астролог</p>
                        <h2>Ради</h2>
                    </header>
                    <div class="image fit">
                        <img src="{% static 'images/rady.jpg' %}" alt=""/>
                    </div>
                    <br>

                    <h3 align=center>зодия Скорпион, с асцендент Водолей и Луна в Козирог</h3>
                    <p align=justify>През живота си съм се занимавала с хиляди неща, но преди няколко години открих
                        любовта на живота си – Астрологията.
                        Винаги ми е било любопитно и интересно, но едва когато се заех сериозно с астрологията открих,
                        че това е страстта ми.
                        Учих се от две звезди в сферата – изключителните Оксана Хорват-Станчева и Кирил Горанов.
                        Сега работя главно за чужбина с прекрасната Лада от <a target="_blank"
                                                                               href="http://www.astrolada.com/readers/radostina.html">astrolada</a>,
                        но се надявам да съм полезна и тук, в България.
                        Използвам и таро, оракулски карти и имам инициация в Рейки II. Винаги съм смятала, че мисията на
                        живота ми е да помагам на хората, да ги мотивирам и вдъхновявам.
                        Правя това от сърце и с благодарност. Ако все още не сте намерили своя път или имате други
                        дилеми, ще се радвам да ги споделите и заедно да намерим решение.</p>

                </div>
                <div class="content">
                    <section id="One" class="wrapper style3">
                        <div class="inner">
                            <header class="align-center">
                                <p>Astrology is a language. If you understand this language, the sky speaks to you.</p>
                                <h2> Dane Rudhyar </h2>
                            </header>
                        </div>

                    </section>

                </div>

            </div>
            <div class="inner">
                <div class="box">
                    <div class="content">
                        <header class="align-center">
                            <h2>Другите за мен:</h2>
                        </header>
                    </div>
                </div>
            </div>
            <div class="inner">
                <div class="grid-style">
                    <div>
                        <div class="box">
                            <div class="content">
                                <header class="align-center">
                                    <h3 align=justify>"Вчера бях на консултация при Ради и беше невероятно!
                                        Тя е прекрасна, усмихната, лъчезарна и слънчева! Изключително съм доволна от
                                        професионализма й и от всичко,което ми каза и разчете :)
                                        Горещо я препоръчвам! Няма да останете разочаровани - само очаровани!
                                        Благодаря ти, Ради! </h3>
                                </header>
                                <footer class="align-center">
                                    <p>Bistra Georgieva </p>
                                </footer>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="box">
                            <div class="content">
                                <header class="align-center">
                                    <h3 align=justify>"Always finds the right words to touch your heart" </h3>
                                </header>
                                <footer class="align-center">
                                    <p>Simona Simeonova</p>
                                </footer>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="box">
                            <div class="content">
                                <header class="align-center">
                                    <h3 align=justify>"I've always been fascinated by astrology and have had many
                                        readings
                                        from various astrologers across Europe. Rady provided one of the most
                                        accurate
                                        readings I have had to date.
                                        I will certainly be asking her for more readings in future!" </h3>
                                </header>
                                <footer class="align-center">
                                    <p>Dale K. </p>
                                </footer>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="box">
                            <div class="content">
                                <header class="align-center">
                                    <h3 align=justify>"Страхотен астролог! Личи си, че говори с много вещина. Много
                                        съм
                                        впечатлена!" </h3>
                                </header>
                                <footer class="align-center">
                                    <p>Monika Nikolova</p>
                                </footer>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="box">
                            <div class="content">
                                <header class="align-center">
                                    <h3 align=justify>"Изключително приятен човек и отличен специалист : ))" </h3>
                                </header>
                                <footer class="align-center">
                                    <p>Павел Петров</p>
                                </footer>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="box">
                            <div class="content">
                                <header class="align-center">
                                    <h3 align=justify>"I always ask Radostina when I have an important decision to
                                        take or
                                        when I am going through some interesting stage in my life.
                                        She has intuition and deep understanding of how the planetary influences
                                        work on our
                                        lives. I strongly recommend her services." </h3>
                                </header>
                                <footer class="align-center">
                                    <p>Nicky S. </p>
                                </footer>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section id="two" class="wrapper style3">
        <div class="inner">
            <header class="align-center">
                <p>Твоят личен астролог</p>
                <h2><a href="{% url 'main_app:contacts' %}">Свържи се с мен</a></h2>
            </header>
        </div>
    </section>

{% endblock %}

templates/main_app/contacts.html
<!DOCTYPE html>
#TODO submit fade-out

{% extends 'base.html' %}
{% block page_title %}
    свържи се с мен
{% endblock %}
{% block body_contents %}
    {% if form.errors %}
        <p>Грешно въведени данни. Моля въведете отново!</p>
    {% endif %}
    <div id="main" class="container">
        <h3>Моля, попълнете формата за контакт и аз ще се свържа с Вас възможно най-скоро!</h3>
        <p style="color:red"><em>полетата отбелязани със *** са задължителни!</em></p>
        <br>
        <form action="{% url 'main_app:contacts' %}" method="post">
            {% csrf_token %}
            <div class="row uniform">
                <div class="6u 12u$(xsmall)">
                    {{ form.names }}
                </div>
                <div class="6u$ 12u$(xsmall)">
                    {{ form.email }}
                </div>
            </div>
            <br>
            <div class="12u$">
                {{ form.phone }}
            </div>
            <br>
            <div class="12u$">
                {{ form.message }}
            </div>
            <br>
            <!-- Break -->
            <div class="12u$">
                <ul class="actions">
                    <li><input type="submit" id="submit-button" value="Изпрати!"></li>
                    <li><input type="reset" class="alt"/></li>
                    <script>
                        $('#submit-button').on('submit', function () {
                            var div_success = $('.container');
                            div_success.eq(1).fadeOut(1500);

                        });
                    </script>
                </ul>
            </div>
        </form>
    </div>


    <div class="container">
        <dl class="align-justify">
            <dt>Други начини за контакт с мен:</dt>
            <dd>
                <p>Телефон: +359 88 428 4207</p>
                <p>Email: <a href="mailto:radyandthestars@gmail.com">radyandthestars@gmail.com</a>
                <p>SKYPE: Radostina.happylina - > <a href="skype:Radostina.happylina?chat">Започни чат</a></p>
                <p>Facebook: <a href="https://www.facebook.com/radyandthestars/">Rady and the stars</a></p>
            </dd>
        </dl>
    </div>


{% endblock %}

templates/main_app/contacts_thank_you.html
{% extends 'base.html' %}
{% block page_title %}
    Благодаря, Ви!
{% endblock %}
{% block body_contents %}
    <div class="container">
        <br><br><br>
        <p>Благодаря, за Вашият въпрос! Ще се свържа с вас възможно най-скоро!</p>
        <p>Моля, натисненете <a href="{% url 'index' %}">тук</a> за да се върнете към началото! </p>
    </div>
{% endblock %}

templates/main_app/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}
{% block page_title %} твоят личен астролог {% endblock %}
{% block body_contents %}



        {#    <section class="banner full">#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/aries.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/taurus.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/gemini.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/cancer.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                    <!-- <p>рак</p>#}
        {#                    <h2>Девиз</h2> -->#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/leo.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/virgo.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/libra.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/scorpio.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/sagittarius.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/capricorn.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/aquarius.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#        <article>#}
        {#            <img src="{% static 'images/slides/pisces.png' %}" alt=""/>#}
        {#            <div class="inner">#}
        {#                <header>#}
        {#                </header>#}
        {#            </div>#}
        {#        </article>#}
        {#    </section>#}

        <!-- One -->
        <section id="one" class="wrapper style2">
            <div class="inner">
                <div class="grid-style">
                    <div>
                        <div class="box">
                            <div class="image fit">
                                <img src="{% static '/images/love.jpg' %}" alt=""/>
                            </div>
                            <div class="content">
                                <header class="align-center">
                                    <p>Интересуваш се от ...</p>
                                    <h2>Любов и взаимоотношения</h2>
                                </header>
                                <p> Любов, връзки, кармични влияния и уроци.
                                    Твоят хороскоп съдържа отговорите на всички въпроси, които имаш относно любовния си
                                    живот.
                                    Какви партньори привличаш и защо? Кои са любовните периоди в живота ти?
                                    Кога да сключиш брак? Каква е съвместимостта с партньора ти и къде е възможно да
                                    срещнете трудности в съвместния ви път?
                                    Всичко това е записано в хороскопа и в комбинацията между две натални карти. </p>
                                <footer class="align-center">
                                    <a href="{% url 'main_app:order' %}" class="button alt">Поръчай Сега!</a>
                                </footer>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="box">
                            <div class="image fit">
                                <img src="{% static '/images/astro.jpg' %}" alt=""/>
                            </div>
                            <div class="content">
                                <header class="align-center">
                                    <p>Търсиш...</p>
                                    <h2>Цялостни астрологични консултации</h2>
                                </header>
                                <p> Хороскопът показва твоят живот, той е като книга, която разказва твоята лична
                                    история.
                                    Тази информация дава знание, показва потенциалите ти, предизвикателствата, пред
                                    които се
                                    изправяш и начините за преодоляването им. Всички уроци и всички възможности, които
                                    стоят
                                    пред теб и вътре в теб са записани в наталната ти карта. Да получиш информация за
                                    живота си чрез езика на астрологияте е истинско духовно пътешествие.</p>
                                <footer class="align-center">
                                    <a href="{% url 'main_app:order' %}" class="button alt">Поръчай Сега!</a>
                                </footer>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="box">
                            <div class="image fit">
                                <img src="{% static '/images/tarrot.jpg' %}" alt=""/>
                            </div>
                            <div class="content">
                                <header class="align-center">
                                    <p>Трябва ти ... </p>
                                    <h2>Таро и оракулски карти</h2>
                                </header>
                                <p> Попитай картите и те ще ти покажат пътя, за да намериш отговори и да живееш в
                                    хармония.</p>
                                <footer class="align-center">
                                    <a href="{% url 'main_app:order' %}" class="button alt">Поръчай Сега!</a>
                                </footer>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="box">
                            <div class="image fit">
                                <img src="{% static '/images/news.jpg' %}" alt=""/>
                            </div>
                            <div class="content">
                                <header class="align-center">
                                    <p>Искаш да видиш...</p>
                                    <h2>Новини и Видео материали</h2>
                                </header>
                                <p>Гледай или прочети материали на различни теми, свързани с астрологията. </p>
                                <footer class="align-center">
                                    <a href="{% url 'main_app:order' %}" class="button alt">Гледай тук!</a>
                                </footer>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Two -->
        <section id="two" class="wrapper style3">
            <div class="inner">
                <header class="align-center">
                    <p>Твоят личен астролог</p>
                    <h2><a href="../main_app/contacts.html">Свържи се с мен</a></h2>
                </header>
            </div>
        </section>
{% endblock %}

templates/main_app/order.html
<!DOCTYPE html>
#TODO submit fade-out
{% extends 'base.html' %}
{% block page_title %}Поръчай онлайн {% endblock %}
{% block body_contents %}
    <div class="container">
        <br>
        <h3>Какво поръчвате:</h3>
        <dl>
            <dt>Пълен хороскоп</dt>
            <dd>
                <p>Описание на услуга 1</p>
            </dd>
            <dt>Item 2</dt>
            <dd>
                <p>Описание на услуга 2.</p>
            </dd>
            <dt>Item 3</dt>
            <dd>
                <p>Описание на услуга 3.</p>
            </dd>
        </dl>
    </div>
    <div id="main" class="container">
        {% if form.errors %}
            <p>Грешно въведени данни. Моля въведете отново!</p>
        {% endif %}
        <form action="{% url 'main_app:order' %}" method="post">
            {% csrf_token %}
            <div class="row uniform">
                <div class="6u 12u$(xsmall)">
                    {{ form.names }}
                </div>
                <div class="6u$ 12u$(xsmall)">
                    {{ form.email }}
                </div>
            </div>
            <br>

            <div class="12u$">
                {{ form.phone }}
            </div>
            <br>
            <div class="12u$">
                <div class="select-wrapper">
                    {{ form.service_requested }}
                </div>
            </div>
            <br>
            <div class="12u$">
                {{ form.add_info }}
            </div>
            <br>
            <!-- Break -->
            <div class="12u$">
                <ul class="actions">
                    <li><input type="submit" id="submit-button" value="ИЗПРАТИ"></li>
                    <li><input type="reset" class="alt" value="ИЗЧИСТИ"></li>
                    <script>
                        $('#submit-button').on('submit', function () {
                            var div_success = $('.container');
                            div_success.eq(2).fadeOut(2000);
                            setTimeout(function () {
                                div_success[1].innerHTML = "<p>Вашата поръчка е получена. Ще се свържа с Вас възможно най-скоро!</p>";
                            }, 2001);
                        });
                    </script>
                </ul>
            </div>
        </form>

    </div>
{% endblock %}

templates/main_app/order_thank_you.html
{% extends 'base.html' %}
{% block page_title %}
    Благодаря, Ви!
{% endblock %}
{% block body_contents %}
    <div class="container">
        <br>
        <p>Благодаря, за Вашата поръчка! Ще се свържа с вас възможно най-скоро!</p>
        <p>Моля, натисненете <a href="{% url 'index' %}">тук</a> за да се върнете към началото! </p>
    </div>
{% endblock %}

templates/main_app/register.html
<!DOCTYPE HTML>

{% extends 'base.html' %}
{% block page_title %}
    регистрирай се
{% endblock %}
{% block body_contents %}
    <div class="container">

        {% if registered %}
            <p>Регистрацията беше успешно! Моля, натистни
                <a href="{% url 'main_app:index' %}">тук </a>
                , за да се върнеш на началната страница!
            </p>
        {% elif  user.is_authenticated %}
            <p>Вече си влезнал! Моля, натистни
                <a href="{% url 'main_app:index' %}">тук </a>
                , за да се върнеш на началната страница!
            </p>
        {% elif passwords_not_match %}
            <p>Въведените пароли не са еднакви! Моля, натистни
                <a href="{% url 'main_app:register' %}"> тук </a>
                , за да въведете отново!
            </p>
        {% else %}
            <form action="{% url 'main_app:register' %}" method="post">
                {% csrf_token %}
                <div class="row uniform">
                    <div class="6u 12u$(xsmall)">
                        {{ register_form }}
                    </div>
                </div>
                <div class="12u$">
                    <ul class="actions">
                        <br>
                        <li><input type="submit" id="submit-button" value="Регистрирай се!"></li>
                    </ul>
                </div>

            </form>
        {% endif %}
    </div>
{% endblock %}