courses/urls.py
from django.urls import re_path
from . import views

app_name = 'courses'
urlpatterns = [
    re_path(r'^$', views.CoursesListView.as_view(), name='courses_index'),
    re_path(r'^(?P<pk>\d+)/$', views.CoursesUrlView.as_view(), name='links')
]

rady_and_stars/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include
from main_app import views
from django.contrib.auth import views as login_view
from . import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^$', views.Index.as_view(), name='index'),
                  url(r'site/', include('main_app.urls')),
                  url(r'userportal/', include('user_content.urls', namespace='user_site')),
                  url(r'login/', login_view.LoginView.as_view(template_name='user_content/login.html'),
                      name='user_login'),
                  url(r'logout/', login_view.logout, name="logout", kwargs={'next_page': 'index'}),
                  url(r'password_reset', login_view.PasswordResetView, name='password_reset'),
                  url(r'admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'__debug__', include(debug_toolbar.urls)),
                  ] + urlpatterns

user_content/urls.py
from django.conf.urls import url, include
from user_content import views
from django.contrib.auth.views import PasswordChangeView

app_name = 'user_content'

urlpatterns = [
    url(r'register/', views.UserRegister.as_view(), name="register"),
    url(r'index/', views.Index.as_view(), name='index'),
    url(r'profile/', views.user_profile_view, name='profile'),
    url(r'horoscope_list/', views.UserHoroscopesListView.as_view(), name="horoscope_list"),
    url(r'detail_text(?P<pk>\d+)/', views.UserHoroscopesDetailView.as_view(), name="detail"),
    url(r'courses/', include('courses.urls', namespace='user_courses')),
    url(r'tarot/', include('tarot_of_the_day.urls', namespace='user_tarot')),
    url(r'daily_tarot_list', views.UserTarotListView.as_view(), name='profile_tarot_list'),
    url(r'daily_tarot_detail(?P<pk>\d+)', views.UserTarotDetailView.as_view(), name='profile_tarot_detail'),
    url(r'daily_tarot_note_edit(?P<pk>\d+)', views.UserTarotNoteUpdateView.as_view(), name='profile__tarot_note_edit'),
    url(r'settings/', views.UserSettingsListView.as_view(), name='settings'),
    url(r'extra_settings_edit', views.UserExtraSettingsUpdateView.as_view(), name='extra_settings'),
    url(r'main_settings_edit', views.UserMainSettingsUpdateView.as_view(), name='main_settings'),
    url(r'password_change',
        PasswordChangeView.as_view(template_name='user_content/profile_settings_password_change.html',
                                   success_url='/login/'),
        name='password_change'),
    url(r'change_avatar', views.profile_pic_upload, name='profile_pic'),
]

user_content/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import os
from django.db.models.signals import post_save


# Create your models here.
def path_and_rename(instance, filename):
    user_id = instance.user_id
    upload_to = 'profile_pics'
    filename = f'{user_id}_profile_pic.png'
    return os.path.join(upload_to, filename)


class SiteUser(models.Model):
    # Описва съдържанието на отделен юзър
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_data')
    birthday = models.DateField(blank=True, null=True)
    hour_of_birth = models.TimeField(blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True)
    used_service = models.BooleanField(choices=((True, "Да"), (False, "Не")), default=False)
    profile_pic = models.ImageField(upload_to=path_and_rename, blank=True)
    city_of_birth = models.CharField(max_length=250, blank=True)
    country_of_birth = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('user_content:profile')

    def null_writer(self, logged_user_id):
        self.user_id = logged_user_id
        self.save()

    def delete_profile_pic(self, logged_user_id):
        filename = f'{logged_user_id}_profile_pic.png'
        print(filename)
        current_dir = os.getcwd()
        media_folder = os.path.join(current_dir, 'media', 'profile_pics')
        os.chdir(media_folder)
        if os.path.exists(filename):
            print('check')
            os.remove(filename)
        os.chdir(current_dir)


class TextsForUser(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    article_text = models.CharField(max_length=20000)

#handle post save call if only new user is created. Links User and SiteUser tables.
def user_post_save_nullwriter_call(sender, instance, created, *args, **kwargs):
    print(created)
    if created:
        SiteUser().null_writer(instance.id)


post_save.connect(user_post_save_nullwriter_call, sender=User)

user_content/forms.py
from django import forms
from django.forms import models
from user_content.models import SiteUser
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm


class SiteUserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')
        labels = {
            'username': "Потребителско име:",
            'password1': "Парола:",
            'password2': "Моля, повторете паролата:",
            'email': 'Email',
        }


class UserRegisterExtraDataForm(models.ModelForm):
    class Meta:
        model = SiteUser
        fields = (
            'phone', 'used_service', 'birthday', 'hour_of_birth', 'city_of_birth',
            'country_of_birth')
        labels = {
            'used_service': 'Използвали ли сте мои услуги досега?',
            'birthday': 'Вашата рожденна дата',
            'hour_of_birth': 'Час на раждане',
            'city_of_birth': 'Град на раждане',
            'country_of_birth': 'Държава на раждане',
            'phone': 'Телефон'
        }


class UserMainDataForm(models.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)


class UserUploadPic(models.ModelForm):
    class Meta:
        model = SiteUser
        fields = ('profile_pic',)
        labels = {'profile_pic': 'Избери профилна снимка от твоят компютър'}

user_content/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView, UpdateView, CreateView, TemplateView
from user_content.forms import SiteUserCreateForm, UserUploadPic
from user_content import models
from tarot_of_the_day import models as tarot_model
from django.urls import reverse_lazy
from user_content.forms import UserRegisterExtraDataForm, UserMainDataForm
from django.contrib.auth import get_user_model


# Create your views here.
class UserRegister(CreateView):
    form_class = SiteUserCreateForm
    success_url = reverse_lazy('user_content:index')
    template_name = 'user_content/register.html'


class Index(LoginRequiredMixin, TemplateView):
    template_name = 'user_content/index.html'


@login_required
def user_profile_view(request):
    username = request.user
    user_main_profile = models.User.objects.filter(username=username)
    user_id = username.id
    user_extra_info = models.SiteUser.objects.filter(user_id=user_id)
    data_dict = {
        'main_info': user_main_profile,
        'extra_info': user_extra_info,
    }
    return render(request, 'user_content/profile_home.html', data_dict)


class UserHoroscopesListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = models.TextsForUser
    context_object_name = 'horoscopes_list'
    template_name = "user_content/profile_horoscope_list_view.html"

    def get_queryset(self):
        queryset = super(UserHoroscopesListView, self).get_queryset()
        username = self.request.user
        queryset = queryset.filter(username=username)
        return queryset


class UserHoroscopesDetailView(LoginRequiredMixin, DetailView):
    model = models.TextsForUser
    login_url = '/login/'
    context_object_name = 'horoscopes_detail'
    template_name = 'user_content/profile_horoscope_detail_view.html'


class UserTarotListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = tarot_model.UserCard
    context_object_name = 'tarot_list'
    template_name = 'user_content/profile_tarot_list.html'

    def get_queryset(self):
        queryset = super(UserTarotListView, self).get_queryset()
        user_id = self.request.user.id
        queryset = queryset.filter(username_id=user_id).order_by('-date_used')
        return queryset


class UserTarotDetailView(LoginRequiredMixin, DetailView):
    model = tarot_model.UserCard
    login_url = '/login/'
    context_object_name = 'tarot_detail'
    template_name = 'user_content/profile_tarot_detail.html'


class UserTarotNoteUpdateView(LoginRequiredMixin, UpdateView):
    model = tarot_model.UserCard
    login_url = '/login/'
    context_object_name = 'note_edit'
    template_name = 'user_content/profile_tarot_note_edit.html'
    fields = ('user_notes',)


class UserSettingsListView(LoginRequiredMixin, ListView):
    model = models.SiteUser
    context_object_name = 'settings_list'
    template_name = 'user_content/profile_settings_list_view.html'

    def get_queryset(self):
        queryset = super(UserSettingsListView, self).get_queryset()
        user_id = self.request.user.id
        queryset = queryset.filter(user_id=user_id)
        return queryset


class UserExtraSettingsUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = models.SiteUser
    form_class = UserRegisterExtraDataForm
    context_object_name = 'user_settings'
    template_name = 'user_content/profile_settings_update_view.html'
    success_url = '/userportal/settings/'

    def get_object(self, queryset=None):
        username_id = self.request.user.id
        queryset = models.SiteUser.objects.get(user_id=username_id)
        return queryset


class UserMainSettingsUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = get_user_model()
    form_class = UserMainDataForm
    context_object_name = 'user_settings'
    template_name = 'user_content/profile_settings_update_view.html'
    success_url = '/userportal/settings/'

    def get_object(self, queryset=None):
        username_id = self.request.user.id
        queryset = self.model.objects.get(id=username_id)
        return queryset


@login_required
def profile_pic_upload(request):
    user_id = request.user.id
    print(user_id)
    content_dict = {}

    # TODO CRITERIAS FOR UPLOAD!
    # content_dict['criteria'] = False

    file_form = UserUploadPic()
    content_dict['form'] = file_form
    if request.method == "POST":
        file_form = UserUploadPic(request.POST)
        if file_form.is_valid():
            if 'profile_pic' in request.FILES:
                models.SiteUser().delete_profile_pic(logged_user_id=user_id)
                uploaded_pic = request.FILES['profile_pic']
                extra_profile_info = models.SiteUser.objects.get(user_id=user_id)
                extra_profile_info.profile_pic = uploaded_pic
                extra_profile_info.save()
        return redirect('user_site:profile')
    return render(request, 'user_content/profile_profile_picture.html', content_dict)

templates/user_content/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}
{% block page_title %}Здравей, {{ user.username }}! {% endblock %}
{% block body_contents %}


    <!-- One -->

    <section id="one" class="wrapper style2">
        <div class="inner">
            <div class="grid-style">
                <div>
                    <div class="box">
                        <div class="image fit">
                            <img src="{% static '/images/love.jpg' %}" alt=""/>
                        </div>
                        <div class="content">
                            <header class="align-center">
                                <p>Твоята...</p>
                                <h2>Таро карта за деня</h2>
                            </header>
                            <p> Описание за Таро карта на деня </p>
                            <footer class="align-center">
                                <a href="{% url 'user_content:tarot_of_the_day:card_of_the_day' %}" class="button alt">Изтегли</a>
                            </footer>
                        </div>
                    </div>
                </div>
                <div>
                    <div class="box">
                        <div class="image fit">
                            <img src="{% static '/images/astro.jpg' %}" alt=""/>
                        </div>
                        <div class="content">
                            <header class="align-center">
                                <p>Трябват ти ...</p>
                                <h2>Видео от курсове</h2>
                            </header>
                            <p> Ако си присъствала на мои курсове, тук ще намериш видеото от курсовете.
                            </p>
                            <footer class="align-center">
                                <a href="{% url 'user_content:courses:courses_index' %}" class="button alt">Виж
                                    видео</a>
                            </footer>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <!-- Two -->
    <section id="two" class="wrapper style3">
        <div class="inner">
            <header class="align-center">
                <p>Твоят личен астролог</p>
                <h2><a href="../main_app/contacts.html">Свържи се с мен</a></h2>
            </header>
        </div>
    </section>
{% endblock %}

templates/user_content/login.html
{% extends 'base.html' %}
{% block page_title %}
    Вход за потребители
{% endblock %}
{% block body_contents %}
    <div class="container">
        <br><br>
        <p style="font-size: 15pt"> Нямаш регистрация??! -
            <a href="{% url 'user_content:register' %}">Регистрирай се</a>
        </p>
        <p style="font-size: 15pt"> Забравена парола ??! -
            <a href="{% url 'user_content:register' %}">Натиснете тук</a>
        </p>
        {% if form.errors %}
            <p>Невалидни данни за вход. Моля, опитайте отново!</p>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Влез">
            <input type="hidden" name="next" value="{{ next }}">
        </form>


    </div>


{% endblock %}

templates/user_content/profile_base.html
<!doctype html>
{% extends 'base.html' %}
{% load staticfiles %}
{% block profile_html_title %}{% endblock %}

{% block header_link_load %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile_page.css' %}">
    <link rel="stylesheet"
          href="https://rawgit.com/FezVrasta/bootstrap-material-design/master/dist/css/material.min.css"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-material-datetimepicker.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

{% block page_title %}
    твоят профил
{% endblock %}
{% block body_contents %}
    <div class="container" style="margin-top: 30px;margin-bottom: 40px">
        <div class="row profile">
            <div class="col-md-3">
                <div class="profile-sidebar">
                    <!-- SIDEBAR USERPIC -->
                    <div class="profile-userpic">

                        <img src="/media/{{ address }}"
                             class="img-responsive"
                             alt="Грешка при зареждане на изображение. Моля, добавете ново изображение!">
                    </div>
                    <!-- END SIDEBAR USERPIC -->
                    <!-- SIDEBAR USER TITLE -->
                    <div class="profile-usertitle">
                        <div class="profile-usertitle-name">
                            {{ user }}
                            <p style="margin-top: 12px"><a class="button" href="{% url 'user_content:profile_pic' %}"
                                                           style="font-size: 12px"><i
                                    class="glyphicon glyphicon-picture"></i> [качи снимка] </a></p>
                        </div>
                    </div>
                    <div class="profile-usermenu">
                        <ul class="nav">
                            <li {% block home_menu %}{% endblock %}>
                                <a href="{% url 'user_content:profile' %}">
                                    <i class="glyphicon glyphicon-home"></i>ИНФО </a>
                            </li>
                            <li {% block settings_menu %}{% endblock %}>
                                <a href="{% url 'user_content:settings' %}">
                                    <i class="glyphicon glyphicon-user"></i>Настройки </a>
                            </li>
                            <li {% block horoscopes_menu %}{% endblock %}>
                                <a href="{% url 'user_content:horoscope_list' %}">
                                    <i class="glyphicon glyphicon-star"></i>Хороскопи </a>
                            </li>

                            <li {% block tarrot_menu %}{% endblock %}>
                                <a href="{% url 'user_content:profile_tarot_list' %}">
                                    <i class="glyphicon glyphicon-calendar"></i>Таро на деня </a>
                            </li>
                        </ul>
                    </div>
                    <!-- END MENU -->
                </div>
            </div>
            <div class="col-md-9">
                <div class="profile-content">

                    {% block profile_content %}
                    {% endblock %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user_content/profile_home.html
{% extends 'user_content/profile_base.html' %}
{% load staticfiles %}
{% block profile_html_title %}
    Профил
{% endblock %}
{% block home_menu %}class="active"{% endblock %}
{% block  profile_content %}

    {% for item in main_info %}
        <h3>Здравей, {{ item.username }}!</h3>
        <p>Това е твоята профилна страница. От тук можеш да:</p>
        <ul>
            <li>Променяш своите данни</li>
            <li>Да прочетеш хороскопи, които съм написала за теб</li>
            <li>Да гледаш видео от лекции, за курсове които си посещавал</li>
            <li>Да прегледаш всички Таро карти за деня, които си изтеглил</li>
        </ul>

        Евентуално поръчки... и тн<br><br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a diam egestas, mattis lacus
        euismod, finibus elit. Pellentesque nulla nunc, sodales id risus vel, sodales rutrum enim.
        Nullam vitae sagittis odio. Praesent tempus cursus lectus, vitae ultrices massa fermentum
        non. Curabitur congue nibh ut convallis tincidunt. Pellentesque habitant morbi tristique
        senectus et netus et malesuada fames ac turpis egestas. Aliquam sed cursus urna. Cras lectus
        urna, mattis ut tellus sit amet, vulputate tincidunt erat. Pellentesque tincidunt ipsum sed
        nibh molestie, non elementum urna dignissim. Fusce tempor elementum justo vitae vehicula.
        Cras ac vehicula nisi. Cras vitae placerat dolor. Nullam suscipit leo vitae nulla malesuada,
        quis interdum nunc varius. Mauris rhoncus nisi nec lorem convallis, id placerat ante
        suscipit. Suspendisse vitae urna ex.

        Vivamus in ultricies leo, non viverra purus. Aliquam sed cursus nunc. Nulla eu varius nulla.
        In hac habitasse platea dictumst. Proin cursus tellus nec quam aliquam euismod. Maecenas non
        ante vel sem condimentum tempor a sed eros. Aenean ultricies non ante id mollis.
    {% endfor %}


{% endblock %}

templates/user_content/profile_horoscope_detail_view.html
<!doctype html>
{% extends 'user_content/profile_base.html' %}
{% load staticfiles %}
{% block profile_html_title %}
    Профил:Хороскопи
{% endblock %}
{% block horoscopes_menu %}
    class="active"
{% endblock %}


{% block page_title %}
    твоят профил - хороскопи
{% endblock %}
{% block profile_content %}

    <h2>{{ horoscopes_detail.title }}</h2>

    <p style="text-align: justify">{{ horoscopes_detail.article_text }}</p>
    <ul class="actions">
        <li><a href="{% url 'user_content:horoscope_list' %}"
               class="button">Обратно</a></li>
    </ul>


{% endblock %}

templates/user_content/profile_horoscope_list_view.html
<!doctype html>
{% extends 'user_content/profile_base.html' %}
{% load staticfiles %}
{% block profile_html_title %}
    Профил:Хороскопи
{% endblock %}
{% block horoscopes_menu %}
    class="active"
{% endblock %}


{% block page_title %}
    твоят профил - хороскопи
{% endblock %}
{% block profile_content %}

    <h3>Твоите хороскопи:</h3>
    <ul>
        {% for item in horoscopes_list %}
            <li><a href="/userportal/detail_text{{ item.id }}">{{ item.title }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

templates/user_content/profile_profile_picture.html
{% extends 'user_content/profile_base.html' %}
{% load staticfiles %}
{% block profile_html_title %}
    Профил:настройки
{% endblock %}

{% block settings_menu %}
    class="active"
{% endblock %}


{% block page_title %}
    твоят профил - настройки
{% endblock %}
{% block profile_content %}


    <div class="box">
        <h4>Изисквания за профилната снимка:</h4>
        <ul>
            <li>Да не е по-голяма от 2 MB</li>
            <li>Минимален размер: 50x50</li>
            <li>Препоръчеителен размер: 150x150</li>

        </ul>
        <form enctype="multipart/form-data" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Изпрати">

        </form>
    </div>


{% endblock %}

templates/user_content/profile_settings_list_view.html
<!doctype html>
{% extends 'user_content/profile_base.html' %}
{% load staticfiles %}
{% block profile_html_title %}
    Профил:настройки
{% endblock %}
{% block header_scripts_load %}
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% endblock %}
{% block settings_menu %}
    class="active"
{% endblock %}


{% block page_title %}
    твоят профил - настройки
{% endblock %}
{% block profile_content %}

    {% for item in settings_list %}
        <div id="accordion">
            <h3 style="margin-bottom: 10px">Основни настройки</h3>
            <div class="box">
                <p style="margin-bottom: 10px">Потребителско
                    име: {{ item.user.username }}</p>
                <p style="margin-bottom: 10px">Парола: <a href="{% url 'user_content:password_change' %}">[Промени
                    парола]</a></p>
                {% if  item.user.first_name  != '' %}
                    <p style="margin-bottom: 10px;">
                        Име: {{ item.user.first_name }}</p>
                {% else %}
                    <p style="margin-bottom: 10px">Име: Не е въведено</p>
                {% endif %}
                {% if  item.user.last_name  != '' %}
                    <p style="margin-bottom: 10px">
                        Фамилия: {{ item.user.last_name }}</p>
                {% else %}
                    <p style="margin-bottom: 10px">Фамилия: Не е въведено</p>
                {% endif %}
                <p style=" margin-bottom: 10px">Email: {{ item.user.email }}</p>
                <br>

                <ul class="actions">
                    <li><a href="{% url 'user_content:main_settings' %}"
                           class="button fit">Редактирай</a></li>
                </ul>
            </div>
            <h3>Допълнителни настройки</h3>
            <div class="box">
                {% if  item.phone  != '' %}
                    <p style="margin-bottom: 10px">Телефон: {{ item.phone }}</p>
                {% else %}
                    <p style="margin-bottom: 10px">Телефон: Не е въведено</p>
                {% endif %}
                {% if  item.birthday  != None %}
                    <p style="margin-bottom: 10px">Дата на раждане: {{ item.birthday }}</p>
                {% else %}
                    <p style="margin-bottom: 10px">Дата на раждане: Не е въведено</p>
                {% endif %}
                {% if  item.hour_of_birth  != None %}
                    <p style="margin-bottom: 10px">Час на
                        раждане: {{ item.hour_of_birth }}</p>
                {% else %}
                    <p style="margin-bottom: 10px">Час на раждане: Не е въведено</p>
                {% endif %}
                {% if  item.city_of_birth  != '' %}
                    <p style="margin-bottom: 10px">Град на раждане: {{ item.city_of_birth }}</p>
                {% else %}
                    <p style="margin-bottom: 10px">Град на раждане: Не е въведено</p>
                {% endif %}
                {% if  item.country_of_birth  != '' %}
                    <p style="margin-bottom: 10px">Държава на
                        раждане: {{ item.country_of_birth }}</p>
                {% else %}
                    <p style="margin-bottom: 10px">Държава на раждане: Не е
                        въведено</p>
                {% endif %}
                <br>
                <ul class="actions">
                    <li><a href="{% url 'user_content:extra_settings' %}"
                           class="button fit">Редактирай</a></li>
                </ul>
            </div>
        </div>

    {% endfor %}
    <script>
        $("#accordion").accordion();
    </script>

{% endblock %}

templates/user_content/profile_settings_password_change.html
<!doctype html>
{% extends 'user_content/profile_base.html' %}
{% load staticfiles %}
{% block profile_html_title %}
    Профил:настройки
{% endblock %}

{% block settings_menu %}
    class="active"
{% endblock %}


{% block page_title %}
    твоят профил - настройки
{% endblock %}
{% block profile_content %}

    <div class="box">
        <form method="POST">
            {{ form.as_p }}

            {% csrf_token %}
            <input type="submit" value="Изпрати">

        </form>
    </div>


{% endblock %}

templates/user_content/profile_settings_update_view.html
<!doctype html>
{% extends 'user_content/profile_base.html' %}
{% load staticfiles %}
{% block profile_html_title %}
    Профил:настройки
{% endblock %}

{% block header_scripts_load %}
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://momentjs.com/downloads/moment-with-locales.min.js"></script>
    <script type="text/javascript"
            src="{% static 'js/bower_components/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' %}"></script>
{% endblock %}
{% block settings_menu %}
    class="active"
{% endblock %}


{% block page_title %}
    твоят профил - настройки
{% endblock %}
{% block profile_content %}

    <div class="box">
        <form method="POST">
            {{ form.as_p }}

            {% csrf_token %}
            <input type="submit" value="Изпрати">

        </form>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_birthday').bootstrapMaterialDatePicker
            ({
                weekStart: 1,
                time: false,
                clearButton: true
            });

            $('#id_hour_of_birth').bootstrapMaterialDatePicker
            ({
                date: false,
                shortTime: false,
                format: 'HH:mm'
            });
        })

    </script>


{% endblock %}

templates/user_content/profile_tarot_detail.html
{% extends 'user_content/profile_base.html' %}
{% load staticfiles %}
{% block profile_html_title %}
    Профил:Таро
{% endblock %}
{% block page_title %}
    твоят профил:таро карти
{% endblock %}
{% block tarrot_menu %}class="active"{% endblock %}
{% block  profile_content %}
    <h3>Твоята карта за {{ tarot_detail.date_used }} e: {{ tarot_detail.date_card.name }}</h3>

    {% with image_static='tarot/'|add:tarot_detail.date_card.picture_name %}
        <div class="row 50% uniform" style="color: #252431; text-align: justify;margin-top: 10px">
        <p style="font-size: 13px">
        <span class="image left"><img src="{% static   image_static %}"></span>
    {% endwith %}
{{ tarot_detail.date_card.meaning }}
</div>
    </p>
    <p>Оставил си тази бележка към картата:</p>
    <p> {{ tarot_detail.user_notes }}</p>
    <ul class="actions">
        <li><a href="./daily_tarot_note_edit{{ tarot_detail.id }}"
               class="button special">Редактирай!</a></li>
        <li><a href="{% url 'user_content:profile_tarot_list' %}"
               class="button">Обратно</a></li>

    </ul>
{% endblock %}