courses/urls.py
from django.urls import re_path
from . import views

app_name = 'courses'
urlpatterns = [
    re_path(r'^$', views.CoursesListView.as_view(), name='courses_index'),
    re_path(r'^(?P<pk>\d+)/$', views.CoursesUrlView.as_view(), name='links')
]

main_app/urls.py
from django.conf.urls import url
from main_app import views

app_name = 'main_app'
urlpatterns = [
    url(r'contacts/$', views.Contacts.as_view(), name="contacts"),
    url('contacts/thank_you/$', views.ContactsThankYou.as_view(), name='contacts_thank_you'),
    url(r'order/$', views.Order.as_view(), name="order"),
    url('order/thank_you/$', views.OrderThankYou.as_view(), name='order_thank_you'),
    url(r'Rady/$', views.Rady.as_view(), name="Rady"),
]

rady_and_stars/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include
from main_app import views
from django.contrib.auth import views as login_view
from . import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^$', views.Index.as_view(), name='index'),
                  url(r'site/', include('main_app.urls')),
                  url(r'userportal/', include('user_content.urls', namespace='user_site')),
                  url(r'login/', login_view.LoginView.as_view(template_name='user_content/login.html'),
                      name='user_login'),
                  url(r'logout/', login_view.logout, name="logout", kwargs={'next_page': 'index'}),
                  url(r'password_reset', login_view.PasswordResetView, name='password_reset'),
                  url(r'admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'__debug__', include(debug_toolbar.urls)),
                  ] + urlpatterns

user_content/urls.py
from django.conf.urls import url, include
from user_content import views
from django.contrib.auth.views import PasswordChangeView

app_name = 'user_content'

urlpatterns = [
    url(r'register/', views.UserRegister.as_view(), name="register"),
    url(r'index/', views.Index.as_view(), name='index'),
    url(r'profile/', views.user_profile_view, name='profile'),
    url(r'horoscope_list/', views.UserHoroscopesListView.as_view(), name="horoscope_list"),
    url(r'detail_text(?P<pk>\d+)/', views.UserHoroscopesDetailView.as_view(), name="detail"),
    url(r'courses/', include('courses.urls', namespace='user_courses')),
    url(r'tarot/', include('tarot_of_the_day.urls', namespace='user_tarot')),
    url(r'daily_tarot_list', views.UserTarotListView.as_view(), name='profile_tarot_list'),
    url(r'daily_tarot_detail(?P<pk>\d+)', views.UserTarotDetailView.as_view(), name='profile_tarot_detail'),
    url(r'daily_tarot_note_edit(?P<pk>\d+)', views.UserTarotNoteUpdateView.as_view(), name='profile__tarot_note_edit'),
    url(r'settings/', views.UserSettingsListView.as_view(), name='settings'),
    url(r'extra_settings_edit', views.UserExtraSettingsUpdateView.as_view(), name='extra_settings'),
    url(r'main_settings_edit', views.UserMainSettingsUpdateView.as_view(), name='main_settings'),
    url(r'password_change',
        PasswordChangeView.as_view(template_name='user_content/profile_settings_password_change.html',
                                   success_url='/login/'),
        name='password_change'),
    url(r'change_avatar', views.profile_pic_upload, name='profile_pic'),
]

templates/base - backup.html
<!DOCTYPE HTML>
{% load staticfiles %}
{% load custom_tags %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    {% block html_title_and_links %}
        <!--<title>&#9733;&#9734;Rady and the Stars&#9734;&#9733; </title>-->
    {% endblock %}
    {% block header_link_load %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>

    <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous">
    </script>
    {% block header_scripts_load %}
    {% endblock %}
</head>
<body>

<!-- Header -->
<header id="header">
    {#<header id="header" class="alt"> за индекса само!#}
    {% if user.is_authenticated %}
        <div class="logo"><a href="{% url 'user_content:index' %}">Rady <span>and the Stars</span></a>
    {% else %}
        <div class="logo"><a href="{% url 'index' %}">Rady <span>and the Stars</span></a>
    {% endif %}
    </div>
    {% if user.is_staff %}
        <a href="../admin">АДМИН</a>
    {% endif %}
    {% if user.is_authenticated %}
        <a href={% url 'logout' %}>Излез</a>
    {% else %}
        <a href="{% url 'user_login' %}">ВХОД</a>
    {% endif %}
    <a href="#menu">МЕНЮ</a>
</header>

<!-- Nav -->
<nav id="menu">
    <ul class="links">
        {% if user.is_authenticated %}
            {% return_menu_items "logged" as site_menu %}
            {% for item,value in site_menu.items %}
                <li><a href="../{{ value.1 }}">{{ value.0 }}</a></li>
            {% endfor %}
        {% else %}
            {% return_menu_items "not_logged" as site_menu %}
            {% for item,value in site_menu.items %}
                <li><a href="../{{ value.1 }}">{{ value.0 }}</a></li>
            {% endfor %}
        {% endif %}
    </ul>
</nav>

<section id="One" class="wrapper style3">
    <div class="inner">
        <header class="align-center">

            <p>
                {% block page_title %}{% endblock %}
            </p>
            <h2>Rady and the Stars</h2>
        </header>
    </div>
</section>

{% block body_contents %}
{% endblock %}

<footer id="footer">
    <div class="container">
        <ul class="icons">
            <li><a href="https://www.facebook.com/radyandthestars/" class="icon fa-facebook"><span class="label">Facebook</span></a>
            </li>
            <li><a href="https://www.instagram.com/rady_and_the_stars/" class="icon fa-instagram"><span class="label">Instagram</span></a>
            </li>
            <li><a href="mailto:radyandthestars@gmail.com" class="icon fa-envelope-o"><span
                    class="label">Email</span></a></li>
        </ul>
        <a href="{% url 'main_app:order' %}">Поръчай услуга</a>
        <a href="{% url 'main_app:Rady' %} ">Rady</a>
        <a href="{% url 'main_app:contacts' %}">Контакт</a>

    </div>
    <div class="copyright">
        &copy; Rady and the stars
    </div>
</footer>

<!-- Scripts -->
<script src="{% static '/js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'js/skel.min.js' %}"></script>
<script src="{% static '/js/util.js' %}"></script>
<script src="{% static '/js/main.js' %}"></script>


</body>
</html>

templates/base.html
<!DOCTYPE HTML>
{% load staticfiles %}
{% load custom_tags %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    {% block html_title_and_links %}
        <!--<title>&#9733;&#9734;Rady and the Stars&#9734;&#9733; </title>-->
    {% endblock %}
    {% block header_link_load %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>

    <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous">
    </script>
    {% block header_scripts_load %}
    {% endblock %}
</head>
<body>

<!-- Header -->

<header id="headermenu">

    <div class="inner">

        {% if user.is_authenticated %}
            <a href="{% url 'user_content:index' %}" class="logo">Rady and the Stars</a>
        {% else %}
            <a href="{% url 'index' %}" class="logo">Rady and the Stars</a>
        {% endif %}


        <nav id="nav">

            {% if user.is_authenticated %}
                {% return_menu_items "logged" as site_menu %}
                {% for item,value in site_menu.items %}
                    <a href="../{{ value.1 }}">{{ value.0 }}</a>
                {% endfor %}
            {% else %}
                {% return_menu_items "not_logged" as site_menu %}
                {% for item,value in site_menu.items %}
                    <a href="../{{ value.1 }}">{{ value.0 }}</a>
                {% endfor %}
            {% endif %}


            {% if user.is_staff %}
                <a href="../admin">АДМИН</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a href={% url 'logout' %}>Излез</a>
            {% else %}
                <a href="{% url 'user_login' %}">ВХОД</a>
            {% endif %}


        </nav>
    </div>
    </div>
</header>
<a href="#menu" class="navPanelToggle"><span class="fa fa-bars"></span></a>


{#Menu - hidden#}

{#<header id="header">#}
{#<header id="header" class="alt"> за индекса само!#}
{#    {% if user.is_authenticated %}#}
{#        <div class="logo"><a href="{% url 'user_content:index' %}">Rady <span>and the Stars</span></a>#}
{#    {% else %}#}
{#        <div class="logo"><a href="{% url 'index' %}">Rady <span>and the Stars</span></a>#}
{#    {% endif %}#}
{#    </div>#}
{#    {% if user.is_staff %}#}
{#        <a href="../admin">АДМИН</a>#}
{#    {% endif %}#}
{#    {% if user.is_authenticated %}#}
{#        <a href={% url 'logout' %}>Излез</a>#}
{#    {% else %}#}
{#        <a href="{% url 'user_login' %}">ВХОД</a>#}
{#    {% endif %}#}
{#    <a href="#menu">МЕНЮ</a>#}
{#</header>#}
{##}
{#<!-- Nav -->#}
{#<nav id="menu">#}
{#    <ul class="links">#}
{#        {% if user.is_authenticated %}#}
{#            {% return_menu_items "logged" as site_menu %}#}
{#            {% for item,value in site_menu.items %}#}
{#                <li><a href="../{{ value.1 }}">{{ value.0 }}</a></li>#}
{#            {% endfor %}#}
{#        {% else %}#}
{#            {% return_menu_items "not_logged" as site_menu %}#}
{#            {% for item,value in site_menu.items %}#}
{#                <li><a href="../{{ value.1 }}">{{ value.0 }}</a></li>#}
{#            {% endfor %}#}
{#        {% endif %}#}
{#    </ul>#}
{#</nav>#}


<section id="One" class="wrapper style3">
    <div class="inner">
        <header class="align-center">

            <p>
                {% block page_title %}{% endblock %}
            </p>
            <h2>Rady and the Stars</h2>
        </header>
    </div>
</section>

{% block body_contents %}
{% endblock %}

<footer id="footer">
    <div class="container">
        <ul class="icons">
            <li><a href="https://www.facebook.com/radyandthestars/" class="icon fa-facebook"><span class="label">Facebook</span></a>
            </li>
            <li><a href="https://www.instagram.com/rady_and_the_stars/" class="icon fa-instagram"><span class="label">Instagram</span></a>
            </li>
            <li><a href="mailto:radyandthestars@gmail.com" class="icon fa-envelope-o"><span
                    class="label">Email</span></a></li>
        </ul>
        <a href="{% url 'main_app:order' %}">Поръчай услуга</a>
        <a href="{% url 'main_app:Rady' %} ">Rady</a>
        <a href="{% url 'main_app:contacts' %}">Контакт</a>

    </div>
    <div class="copyright">
        &copy; Rady and the stars
    </div>
</footer>

<!-- Scripts -->
<script src="{% static '/js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'js/skel.min.js' %}"></script>
<script src="{% static '/js/util.js' %}"></script>
<script src="{% static '/js/main.js' %}"></script>
<script src="{% static '/js/main_static_menu.js' %}"></script>


</body>
</html>